In [2]:
import pandas as pd

pd.__version__

'2.2.2'

In [49]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"
df = pd.read_csv(url)

In [51]:
print(len(df))

2160


In [52]:
unique_brands = df['Brand'].unique()
print(len(unique_brands))
unique_brands

27


array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [53]:
print(df.isnull().sum())

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64


In [56]:
dell_laptops = df.loc[df['Brand'] == 'Dell']
dell_max_price = dell_laptops['Final Price'].max()
print(dell_max_price)
dell_laptops.sort_values(by=['Final Price'], ascending=False)

3936.0


Laptop       Status Brand  \
1335  Dell Precision 5770 Intel Core i7-12700H/16GB/...          New  Dell   
1334  Dell Precision 5470 Intel Core i7-12800H/16GB/...          New  Dell   
1346  Dell XPS 15 9520 Intel Core i7-12700H/16GB RAM...          New  Dell   
1347  Dell XPS 15 9520 Intel Core i7-12700H/32GB/1TB...  Refurbished  Dell   
1323  Dell Latitude 5520 Intel Core i5-1135G7/8GB/25...          New  Dell   
...                                                 ...          ...   ...   
1839  Dell Latitude E5550 Intel Core i5-5300U/8GB/12...  Refurbished  Dell   
1836  Dell Latitude 5480 Intel Core i5-7300U/8GB/256...  Refurbished  Dell   
809   Dell Latitude E7450 Intel Core i5-5300U/8GB/25...  Refurbished  Dell   
1843  Dell Vostro 5301 Intel Core i5-1135G7/8GB/256G...  Refurbished  Dell   
633   Dell Latitude E5440 Intel Core i5-4310U/8GB/12...  Refurbished  Dell   

          Model            CPU  RAM  Storage Storage type        GPU  Screen  \
1335  Precision  Intel Core i7   16      512          SSD  RTX A2000    17.0   
1334  Precision  Intel Core i7   16      512          SSD  RTX A1000    14.0   
1346        XPS  Intel Core i7   16     1000          SSD   RTX 3050    15.6   
1347        XPS  Intel Core i7   32     1000          SSD   RTX 3050    15.6   
1323   Latitude  Intel Core i5    8      256          SSD        NaN    15.6   
...         ...            ...  ...      ...          ...        ...     ...   
1839   Latitude  Intel Core i5    8      128          SSD        NaN    15.6   
1836   Latitude  Intel Core i5    8      256          SSD        NaN    14.0   
809    Latitude  Intel Core i5    8      256          SSD        NaN    14.0   
1843     Vostro  Intel Core i5    8      256          SSD        NaN    13.3   
633    Latitude  Intel Core i5    8      128          SSD        NaN    14.0   

     Touch  Final Price  
1335   Yes      3936.00  
1334    No      3469.00  
1346    No      3012.09  
1347   Yes      2818.09  
1323    No      2450.71  
...    ...          ...  
1839    No       489.00  
1836    No       489.00  
809     No       448.99  
1843    No       420.74  
633     No       379.00  

[84 rows x 12 columns]

In [72]:
median_screen_size = df['Screen'].median()
print('Initial median screen size: ' + str(median_screen_size))
mode_screen_size = df['Screen'].mode().iloc[0]
print('Most frequent screen size (mode): ' + str(mode_screen_size))
df['Screen'] = df['Screen'].fillna(value=mode_screen_size)
median_screen_size = df['Screen'].median()
print('New median screen size: ' + str(median_screen_size))

Initial median screen size: 15.6
Most frequent screen size (mode): 15.6
New median screen size: 15.6


In [83]:
injoo_laptops = df.loc[df['Brand'] == 'Innjoo']
injoo_laptops

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [89]:
injoo_laptops = injoo_laptops[['RAM', 'Storage', 'Screen']]
injoo_laptops

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [95]:
import numpy as np

#Convert injoo_laptops dataframe in Numpy Array X
X = injoo_laptops.values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [98]:
#Compute Transpose Matrix T using X.T
T = X.T
T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [105]:
#Add helper methods from https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/01-intro/08-linear-algebra.md
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

#Compute Matrix between X and Transpose of X (XTX)
XTX = matrix_matrix_multiplication(T,X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [106]:
#Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [111]:
Y = np.array([1100, 1300, 800, 900, 1000, 1100])
Y

intermediary = matrix_matrix_multiplication(XTX_inv, T)
w = matrix_vector_multiplication(intermediary, y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [113]:
sum_of_w = sum(w)
sum_of_w

91.29988062995524